### ISSUE TITLE
UnboundLocalError when distance is not part of the Strava activity

### ISSUE THREAD

**Issue by jat255** [jat255/strava-to-fittrackee#12]
Reported by @bonswouar in #10:

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/bonswouar/git/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1124, in <module>
    sync_strava_with_fittrackee()
  File "/home/bonswouar/git/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1061, in sync_strava_with_fittrackee
    act = strava.create_activity_from_strava(a, get_streams=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bonswouar/git/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 491, in create_activity_from_strava
    velocity=velocity,
             ^^^^^^^^
UnboundLocalError: cannot access local variable 'distance' where it is not associated with a value
```

**Comment by jat255** [comment]
Fixed by #10/#17
