### ISSUE TITLE
Virtual ride causes error and is not synced

### ISSUE THREAD

**Issue by jat255** [jat255/strava-to-fittrackee#13]
```
EBUG:s2f:Marking Strava activitiy 895819xxxx at 2023-04-26T02:42:05Z as needing to be processed
DEBUG:s2f:Processing Strava activity 895820xxxx
DEBUG:s2f:Getting latitude and longitude for activity 895820xxxx
DEBUG:s2f:Current API usage -- 15 minute: 10/100 -- daily: 25/1000
DEBUG:s2f:Getting timepoints for activity 895820xxxx
DEBUG:s2f:Current API usage -- 15 minute: 11/100 -- daily: 26/1000
DEBUG:s2f:Getting altitude for activity 895820xxxx
DEBUG:s2f:Current API usage -- 15 minute: 12/100 -- daily: 27/1000
DEBUG:s2f:Getting velocity for activity 895820xxxx
DEBUG:s2f:Current API usage -- 15 minute: 13/100 -- daily: 28/1000
DEBUG:s2f:Current API usage -- 15 minute: 14/100 -- daily: 29/1000
DEBUG:s2f:POSTing workout with no GPX to FitTrackee
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fittrackee/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1121, in <module>
    sync_strava_with_fittrackee()
  File "/home/fittrackee/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1064, in sync_strava_with_fittrackee
    fittrackee.upload_no_gpx(act)
  File "/home/fittrackee/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 873, in upload_no_gpx
    r.raise_for_status()
  File "/home/fittrackee/strava-to-fittrackee/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fittrackee.myserver.com/api/workouts/no_gpx
DEBUG:s2f:Removing <TemporaryDirectory '/tmp/tmpgqzvz6y2'>
DEBUG:s2f:Removing /home/fittrackee/strava-to-fittrackee/strava_to_fittrackee/s2f.pid
```

Haven't debugged exactly why the request is bad yet.

**Comment by jat255** [comment]
This was actually not an issue with the 'VirtualRide' type in Strava, but rather a "Ride" activity recorded with my Garmin that didn't have any distance or GPX data attached. Closing since that was a one-off mistake and I don't expect to see it again.
