### ISSUE TITLE
When I upload a gpx file, a fatal error occurs.

### ISSUE THREAD

**Issue by ghost** [jat255/strava-to-fittrackee#23]
```bash
root@racknerd-6ce5c6:/opt/strava-to-fittrackee# poetry run python -m strava_to_fittrackee.s2f --upload-all-fittrackee
Uploading GPX files:   0%|                                                                                                | 0/353 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1185, in <module>
    upload_all_fittrackee(args.input_folder)
  File "/opt/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1045, in upload_all_fittrackee
    fittrackee.upload_gpx(f)
  File "/opt/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 832, in upload_gpx
    activity_dict = json.loads(gpx.tracks[0].comment)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by jat255** [comment]
Hard to say what the issue could be without more detail... is it possible for you to debug a little, or share the gpx file that's causing an issue?

**Comment by ghost** [comment]
I downloaded all the strava gpx and then uploaded it to fittrackee, maybe some gpx formats are not supported. Later on, I just sync and it ignores some gpx files that don't match the format.

**Comment by jat255** [comment]
Glad you figured out a workaround. GPX files can have a lot of particularities, so I'm sure not every type of workout file is well-supported.
