### ISSUE TITLE
Excuse me, first of all thank you for the tool. When I synchronize, I always get an error at this location, how can I troubleshoot it.

### ISSUE THREAD

**Issue by ghost** [jat255/strava-to-fittrackee#24]
poetry run python -m strava_to_fittrackee.s2f --sync -v 2 

```bash
DEBUG:s2f:Current API usage -- 15 minute: 56/200 -- daily: 339/2000
DEBUG:s2f:Writing Strava activity gpx to /tmp/tmpdriwgwl9/8234648116.gpx
INFO:s2f:Uploading workout 1 of 146 to FitTrackee
DEBUG:s2f:Uploading /tmp/tmpdriwgwl9/8234648116.gpx to FitTrackee
INFO:s2f:Rewriting GPX file without comment field
DEBUG:s2f:POSTing /tmp/tmpdriwgwl9/8234648116.gpx to FitTrackee
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1189, in <module>
    sync_strava_with_fittrackee()
  File "/opt/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 1142, in sync_strava_with_fittrackee
    fittrackee.upload_gpx(temp_file)
  File "/opt/strava-to-fittrackee/strava_to_fittrackee/s2f.py", line 884, in upload_gpx
    r.raise_for_status()
  File "/root/.cache/pypoetry/virtualenvs/strava-to-fittrackee-MJ8iXs7D-py3.10/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://fit-track.writely.xyz/api/workouts
DEBUG:s2f:Removing <TemporaryDirectory '/tmp/tmpdriwgwl9'>
DEBUG:s2f:Removing /opt/strava-to-fittrackee/strava_to_fittrackee/s2f.pid
```

**Comment by ghost** [comment]
I found the solution, nginx limits the file upload size.
