### ISSUE TITLE
"Treadmill Run" (i.e. activity without GPS) breaks s2f syncing

### ISSUE THREAD

**Issue by jat255** [jat255/strava-to-fittrackee#6]
Recorded a treadmill run with my Garmin Forerunner watch and noticed the syncing action barfing on reading altitude.  This part should be more defensive. Relevant log section:

```
DEBUG:s2f:Processing Strava activity 886878xxxx
DEBUG:s2f:Getting latitude and longitude for activity 886878xxxx
DEBUG:s2f:Current API usage -- 15 minute: 3/100 -- daily: 173/1000
DEBUG:s2f:Getting timepoints for activity 886878xxxx
DEBUG:s2f:Current API usage -- 15 minute: 4/100 -- daily: 174/1000
DEBUG:s2f:Getting altitude for activity 886878xxxx
DEBUG:s2f:Current API usage -- 15 minute: 5/100 -- daily: 175/1000
Traceback (most recent call last):
  File "/home/fittrackee/strava-to-fittrackee/s2f.py", line 943, in <module>
    sync_strava_with_fittrackee()
  File "/home/fittrackee/strava-to-fittrackee/s2f.py", line 889, in sync_strava_with_fittrackee
    act = strava.create_activity_from_strava(a, get_streams=True)
  File "/home/fittrackee/strava-to-fittrackee/s2f.py", line 414, in create_activity_from_strava
    altitude = r.json()[1]["data"]
IndexError: list index out of range
```

**Comment by jat255** [comment]
Resolved by #7
